on: push
name: Check & Release
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: lint
        uses: Roang-zero1/factorio-mod-luacheck@master
        with:
          LUACHECKRC_URL: https://raw.githubusercontent.com/Nexela/Factorio-luacheckrc/0.17/.luacheckrc
  release-modportal:
    runs-on: ubuntu-latest
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Create Factorio mod package
        uses: thattomperson/faketorio-package@master
      - name: Factorio release
        uses: thattomperson/faketorio-upload@master
        with:
          factorio_user: ${{ secrets.FACTORIO_USER }}
          factorio_password: ${{ secrets.FACTORIO_PASSWORD }}
